version = $(shell git describe --long)
major_version = $(shell git describe --abbrev=0)

export DEBFULLNAME := Mika Eloranta
export DEBEMAIL := mika.eloranta@gmail.com

rpm: poni/version.py
	git archive -o rpm-src-poni.tar --prefix=poni/ HEAD
	# add poni/version.py to the tar, it's not in git repository
	tar -r -f rpm-src-poni.tar --transform=s-poni-poni/poni- poni/version.py
	rpmbuild -ta rpm-src-poni.tar \
		--define 'major_version $(major_version)' \
		--define 'minor_version $(subst -,.,$(subst $(major_version)-,,$(version)))'
	$(RM) rpm-src-poni.tar

deb: poni/version.py
	cp debian/changelog.in debian/changelog
	dch -v $(version) -D unstable "Automatic change log entry generated by make"
	dpkg-buildpackage -A -us -uc

.PHONY: debian
